"""empty message

Revision ID: 713f50736a67
Revises: f258fda96a83
Create Date: 2020-04-29 19:05:05.946587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713f50736a67'
down_revision = 'f258fda96a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('shelf_located', sa.Integer(), nullable=True),
    sa.Column('type_category', sa.String(length=60), nullable=True),
    sa.Column('kosher_category', sa.String(length=60), nullable=True),
    sa.Column('expiration_date', sa.DATE(), nullable=True),
    sa.Column('place_taken', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('refrigerators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=True),
    sa.Column('place_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelves')
    op.drop_table('refrigerators')
    op.drop_table('items')
    # ### end Alembic commands ###
