"""empty message

Revision ID: ae10100c1f29
Revises: 713f50736a67
Create Date: 2020-04-30 18:38:49.665311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae10100c1f29'
down_revision = '713f50736a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelves', sa.Column('refrigerator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shelves', 'refrigerators', ['refrigerator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shelves', type_='foreignkey')
    op.drop_column('shelves', 'refrigerator_id')
    # ### end Alembic commands ###
