"""empty message

Revision ID: aea8d286690e
Revises: 74c1ddec5cea
Create Date: 2020-05-09 13:36:28.862482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea8d286690e'
down_revision = '74c1ddec5cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelves', sa.Column('place_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelves', 'place_left')
    # ### end Alembic commands ###
