"""empty message

Revision ID: b2d0784160cf
Revises: 17ef7d341060
Create Date: 2020-05-04 18:06:33.781687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2d0784160cf'
down_revision = '17ef7d341060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'shelf_located')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('shelf_located', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
